version: '3'
services:
  web:
    build: .
    ports:
      - '3000:3000'
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
    depends_on:
      - db
      - chrome
    environment:
      # - "SELENIUM_DRIVER_URL=http://selenium_chrome:4444/wd/hub"
      - "SELENIUM_DRIVER_URL=http://chrome:4444/wd/hub"
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
  chrome:
    # image: selenium/standalone-chrome:latest
    image: selenium/standalone-chrome-debug:latest
    # ports:
    #   - 4444:4444
      # - 5900:5900
    logging:
      driver: none
volumes:
  bundle:
  mysql_data:
